<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OnnxRuntimeSharp/OnnxRuntimeSharp.csproj" />
    <PackageReference Include="IHFood.DependencyResolving" Version="1.0.1" />
    <PackageReference Include="NtvLibs.OnnxRuntime.CPU.cuda13.Tensorrt.runtime.win-x64" Version="1.28.0" />
    <PackageReference Include="NtvLibs.TensorRT.cuda13.runtime.win-x64" Version="10.14.1.48" />
    <PackageReference Include="NtvLibs.cuDNN.cuda13.runtime.win-x64" Version="9.23.0.39" />
    <PackageReference Include="NtvLibs.zlib.zlibwapi.runtime.win-x64" Version="1.3.1" />
    <PackageReference Include="NtvLibs.cuda13.cublas.runtime.win-x64" Version="13.3.0" />
    <PackageReference Include="NtvLibs.MSVCP.runtime.win-x64" Version="14.42.34430" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\models\mnist-8.onnx" Link="mnist-8.onnx" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
