<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>OnnxRuntimeSharp</RootNamespace>
    <AssemblyName>OnnxRuntimeSharp</AssemblyName>
    <IsPackable>true</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsTrimmable>true</IsTrimmable>
    <IsAotCompatible>true</IsAotCompatible>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <EnableAOTAnalyzer>true</EnableAOTAnalyzer>
    <Description>Low-level ONNX Runtime C API interop in modern C#. Cross-platform, trimmable and AOT/NativeAOT compatible.</Description>
    <PackageId>OnnxRuntimeSharp</PackageId>
    <PackageTags>onnx;onnxruntime;interop;nativeaot;low-level;dotnet</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/nietras/OnnxRuntimeSharp/</PackageProjectUrl>
    <PackageReleaseNotes>https://github.com/nietras/OnnxRuntimeSharp/releases</PackageReleaseNotes>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RepositoryUrl>https://github.com/nietras/OnnxRuntimeSharp/</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>OnnxRuntimeSharp.Test</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
